public class Picture
{
    private Square tealwall;
    private Square tealwall2;
    private Square tealwall3;
    private Square tealwall4;
    private Square tealwall5;
    private Square squareroof;
    private Square squareroof2;
    private Square squareroof3;
    private Square squareroof4;
    private Square squareroof5;
    private Square squareroof6;
    private Square squareroof7;
    private Square chimney;
    private Square chimney2;
    private Square chimney3;
    private Square chimney4;
    private Square chimney5;
    private Square window;
    private Square window2;
    private Square window3;
    private Square tealwindow;
    private Square tealwindow2;
    private Square tealwindow3;
    private Square floor;
    private Square grass;
    private Square door;
    private Square door2;
    private Square plantwall;
    private Square plantwall2;
    private Square plantwall3;
    private Square plantwall4;
    private Square plantwall5;
    private Square plantwall6;
    private Square plantwall7;
    private Square plantwall8;
    private Square plantwall9;
    private Square plantwall10;
    private Square plantwall11;
    private Square plantwall12;
    private Square plantwall13;
    private Square plantwall14;
    private Square plantwall15;
    private Square plantwall16;
    private Square plantwall17;
    private Square entrancefloor;
    private Square entrancefloor2;
    private Square entrancefloor3;
    private Square entrancefloor4;
    private Square entrancefloor5;
    private Square pole;
    private Square pole2;
    private Square pole3;
    private Square pole4;
    private Square pole5;
    private Square pole6;
    private Square pole7;
    private Square pole8;
    private Square pole9;
    private Square pole10;
    private Square pole11;
    private Square pole12;
    private Square pole13;
    private Square pole14;
    private Square pole15;
    private Square pole16;
    private Square pole17;
    private Square pole18;
    private Square pole19;
    private Square pole20;
    private Square pole21;
    private Square pole22;
    private Square pole23;
    private Square pole24;
    private Square pole25;
    private Square pole26;
    private Square pole27;
    private Square pole28;
    private Square pole29;
    private Square pole30;
    private Square pole31;
    private Square pole32;
    private Triangle roof;
    private Triangle roof2;
    private Triangle tealroof;
    private Triangle brownroof;
    private Triangle brownroof2;
    private Triangle brownroof3;
    private Triangle whiteroof;
    private Circle sun;
    private Circle handle;
    private Circle bush;
    private Circle bush2;
    private Circle bush3;
    private Circle bush4;
    private Circle bush5;
    private Circle bush6;
    private Circle bush7;
    private Circle bush8;
    private Circle bush9;
    private Circle bush10;
    private Circle bush11;
    private Circle bush12;
    private Circle bush13;
    private Circle bush14;
    private Circle bush15;
    private Circle bush16;
    private Circle bush17;
    private Circle bush18;
    private Circle bush19;
    private Circle bush20;
    private Circle bush21;
    private Circle bush22;
    private Circle bush23;
    private Circle bush24;
    private Circle bush25;
    private Circle bush26;
    private Circle bush27;
    private Circle bush28;
    private Circle bush29;
    private Circle bush30;
    private Person person;

    private boolean drawn;

    /**
     * Constructor for objects of class Picture
     */
    public Picture()
    {
        tealwall = new Square();
        tealwall2 = new Square();
        tealwall3 = new Square();
        tealwall4 = new Square();
        tealwall5 = new Square();
        squareroof = new Square();
        squareroof2 = new Square();
        squareroof3 = new Square();
        squareroof4 = new Square();
        squareroof5 = new Square();
        squareroof6 = new Square();
        squareroof7 = new Square();
        chimney = new Square();
        chimney2 = new Square();
        chimney3 = new Square();
        chimney4 = new Square();
        chimney5 = new Square();
        floor = new Square();
        grass = new Square();
        door = new Square();
        door2 = new Square();
        entrancefloor = new Square();
        entrancefloor2 = new Square();
        entrancefloor3 = new Square();
        entrancefloor4 = new Square();
        entrancefloor5 = new Square();
        window = new Square();
        window2 = new Square();
        window3 = new Square();
        tealwindow = new Square();
        tealwindow2 = new Square();
        tealwindow3 = new Square();
        plantwall = new Square();
        plantwall2 = new Square();
        plantwall3 = new Square();
        plantwall4 = new Square();
        plantwall5 = new Square();
        plantwall6 = new Square();
        plantwall7 = new Square();
        plantwall8 = new Square();
        plantwall9 = new Square();
        plantwall10 = new Square();
        plantwall11 = new Square();
        plantwall12 = new Square();
        plantwall13 = new Square();
        plantwall14 = new Square();
        plantwall15 = new Square();
        plantwall16 = new Square();
        plantwall17 = new Square();
        pole = new Square();
        pole2 = new Square();
        pole3 = new Square();
        pole4 = new Square();
        pole5 = new Square();
        pole6 = new Square();
        pole7 = new Square();
        pole8 = new Square();
        pole9 = new Square();
        pole10 = new Square();
        pole11 = new Square();
        pole12 = new Square();
        pole13 = new Square();
        pole14 = new Square();
        pole15 = new Square();
        pole16 = new Square();
        pole17 = new Square();
        pole18 = new Square();
        pole19 = new Square();
        pole20 = new Square();
        pole21 = new Square();
        pole22 = new Square();
        pole23 = new Square();
        pole24 = new Square();
        pole25 = new Square();
        pole26 = new Square();
        pole27 = new Square();
        pole28 = new Square();
        pole29 = new Square();
        pole30 = new Square();
        roof = new Triangle();
        roof2 = new Triangle();
        tealroof = new Triangle();
        brownroof = new Triangle();
        brownroof2 = new Triangle();
        brownroof3 = new Triangle();
        whiteroof = new Triangle();
        sun = new Circle();
        handle = new Circle();
        bush = new Circle();
        bush2 = new Circle();
        bush3 = new Circle();
        bush4 = new Circle();
        bush5 = new Circle();
        bush6 = new Circle();
        bush7 = new Circle();
        bush8 = new Circle();
        bush9 = new Circle();
        bush10 = new Circle();
        bush11 = new Circle();
        bush12 = new Circle();
        bush13 = new Circle();
        bush14 = new Circle();
        bush15 = new Circle();
        bush16 = new Circle();
        bush17 = new Circle();
        bush18 = new Circle();
        bush19 = new Circle();
        bush20 = new Circle();
        bush21 = new Circle();
        bush22 = new Circle();
        bush23 = new Circle();
        bush24 = new Circle();
        bush25 = new Circle();
        bush26 = new Circle();
        bush27 = new Circle();
        bush28 = new Circle();
        bush29 = new Circle();
        bush30 = new Circle();
        person = new Person();
        drawn = false;
    }

    public static void main(String[] args) {
        Picture picture = new Picture();
        picture.draw();
    }

    /**
     * Draw this picture.
     */
    public void draw()
    {
        if(!drawn) {
            floor.changeColor("gray");
            floor.moveHorizontal(-110);
            floor.moveVertical(300);
            floor.changeSize(530);
            floor.makeVisible();
            grass.changeColor("green");
            grass.moveHorizontal(385);
            grass.moveVertical(460);
            grass.changeSize(390);
            grass.makeVisible();
            chimney.changeColor("maroon");
            chimney.moveHorizontal(-110);
            chimney.moveVertical(11);
            chimney.changeSize(89);
            chimney.makeVisible();
            chimney2.changeColor("maroon");
            chimney2.moveHorizontal(-110);
            chimney2.moveVertical(100);
            chimney2.changeSize(100);
            chimney2.makeVisible();
            chimney3.changeColor("maroon");
            chimney3.moveHorizontal(-110);
            chimney3.moveVertical(200);
            chimney3.changeSize(100);
            chimney3.makeVisible();
            chimney4.changeColor("maroon");
            chimney4.moveHorizontal(-110);
            chimney4.moveVertical(290);
            chimney4.changeSize(100);
            chimney4.makeVisible();
            chimney5.changeColor("maroon");
            chimney5.moveHorizontal(-110);
            chimney5.moveVertical(330);
            chimney5.changeSize(100);
            chimney5.makeVisible();
            squareroof.changeColor("brown");
            squareroof.moveHorizontal(630);
            squareroof.moveVertical(191);
            squareroof.changeSize(140);
            squareroof.makeVisible();
            squareroof2.changeColor("brown");
            squareroof2.moveHorizontal(511);
            squareroof2.moveVertical(191);
            squareroof2.changeSize(140);
            squareroof2.makeVisible();
            tealwall.changeColor("teal");
            tealwall.moveHorizontal(385);
            tealwall.moveVertical(250);
            tealwall.changeSize(290);
            tealwall.makeVisible();
            tealwall2.changeColor("teal");
            tealwall2.moveHorizontal(485);
            tealwall2.moveVertical(250);
            tealwall2.changeSize(290);
            tealwall2.makeVisible();
            tealwall3.changeColor("teal");
            tealwall3.moveHorizontal(260);
            tealwall3.moveVertical(240);
            tealwall3.changeSize(190);
            tealwall3.makeVisible();
            tealwall4.changeColor("teal");
            tealwall4.moveHorizontal(100);
            tealwall4.moveVertical(240);
            tealwall4.changeSize(190);
            tealwall4.makeVisible();
            tealwall5.changeColor("teal");
            tealwall5.moveHorizontal(-70);
            tealwall5.moveVertical(240);
            tealwall5.changeSize(190);
            tealwall5.makeVisible();
            door.changeColor("white");
            door.moveHorizontal(170);
            door.moveVertical(280);
            door.changeSize(80);
            door.makeVisible();
            door2.changeColor("white");
            door2.moveHorizontal(170);
            door2.moveVertical(350);
            door2.changeSize(80);
            door2.makeVisible();
            entrancefloor.changeColor("darkgray");
            entrancefloor.moveHorizontal(170);
            entrancefloor.moveVertical(430);
            entrancefloor.changeSize(80);
            entrancefloor.makeVisible();
            entrancefloor2.changeColor("darkgray");
            entrancefloor2.moveHorizontal(170);
            entrancefloor2.moveVertical(510);
            entrancefloor2.changeSize(80);
            entrancefloor2.makeVisible();
            entrancefloor3.changeColor("darkgray");
            entrancefloor3.moveHorizontal(170);
            entrancefloor3.moveVertical(590);
            entrancefloor3.changeSize(80);
            entrancefloor3.makeVisible();
            entrancefloor4.changeColor("darkgray");
            entrancefloor4.moveHorizontal(170);
            entrancefloor4.moveVertical(670);
            entrancefloor4.changeSize(80);
            entrancefloor4.makeVisible();
            entrancefloor5.changeColor("darkgray");
            entrancefloor5.moveHorizontal(170);
            entrancefloor5.moveVertical(700);
            entrancefloor5.changeSize(80);
            entrancefloor5.makeVisible();
            roof.changeColor("brown");
            roof.changeSize(60, 60);
            roof.moveHorizontal(870);
            roof.moveVertical(170);
            roof.makeVisible();
            roof2.changeColor("brown");
            roof2.changeSize(60, 60);
            roof2.moveHorizontal(610);
            roof2.moveVertical(170);
            roof2.makeVisible();
            brownroof.changeColor("brown");
            brownroof.changeSize(80, 264);
            brownroof.moveHorizontal(740);
            brownroof.moveVertical(92);
            brownroof.makeVisible();
            brownroof2.changeColor("brown");
            brownroof2.changeSize(200, 98);
            brownroof2.moveHorizontal(850);
            brownroof2.moveVertical(30);
            brownroof2.makeVisible();
            brownroof3.changeColor("brown");
            brownroof3.changeSize(200, 98);
            brownroof3.moveHorizontal(50);
            brownroof3.moveVertical(30);
            brownroof3.makeVisible();


            window.changeColor("white");
            window.moveHorizontal(-23);
            window.moveVertical(280);
            window.changeSize(70);
            window.makeVisible();
            window2.changeColor("white");
            window2.moveHorizontal(47);
            window2.moveVertical(280);
            window2.changeSize(70);
            window2.makeVisible();
            window3.changeColor("white");
            window3.moveHorizontal(290);
            window3.moveVertical(280);
            window3.changeSize(70);
            window3.makeVisible();
            tealwindow.changeColor("teal2");
            tealwindow.moveHorizontal(52);
            tealwindow.moveVertical(290);
            tealwindow.changeSize(50);
            tealwindow.makeVisible();
            tealwindow2.changeColor("teal2");
            tealwindow2.moveHorizontal(-8);
            tealwindow2.moveVertical(290);
            tealwindow2.changeSize(50);
            tealwindow2.makeVisible();
            tealwindow3.changeColor("teal2");
            tealwindow3.moveHorizontal(300);
            tealwindow3.moveVertical(290);
            tealwindow3.changeSize(50);
            tealwindow3.makeVisible();
            pole.changeColor("teal3");
            pole.moveHorizontal(450);
            pole.moveVertical(250);
            pole.changeSize(30);
            pole.makeVisible();
            pole2.changeColor("teal3");
            pole2.moveHorizontal(450);
            pole2.moveVertical(280);
            pole2.changeSize(30);
            pole2.makeVisible();
            pole3.changeColor("teal3");
            pole3.moveHorizontal(450);
            pole3.moveVertical(310);
            pole3.changeSize(30);
            pole3.makeVisible();
            pole4.changeColor("teal3");
            pole4.moveHorizontal(450);
            pole4.moveVertical(340);
            pole4.changeSize(30);
            pole4.makeVisible();
            pole5.changeColor("teal3");
            pole5.moveHorizontal(450);
            pole5.moveVertical(370);
            pole5.changeSize(30);
            pole5.makeVisible();
            pole6.changeColor("teal3");
            pole6.moveHorizontal(450);
            pole6.moveVertical(400);
            pole6.changeSize(30);
            pole6.makeVisible();
            pole7.changeColor("teal3");
            pole7.moveHorizontal(450);
            pole7.moveVertical(370);
            pole7.changeSize(30);
            pole7.makeVisible();
            pole8.changeColor("teal3");
            pole8.moveHorizontal(450);
            pole8.moveVertical(400);
            pole8.changeSize(30);
            pole8.makeVisible();
            pole9.changeColor("teal3");
            pole9.moveHorizontal(450);
            pole9.moveVertical(430);
            pole9.changeSize(30);
            pole9.makeVisible();

            pole10.changeColor("teal3");
            pole10.moveHorizontal(530);
            pole10.moveVertical(250);
            pole10.changeSize(30);
            pole10.makeVisible();
            pole11.changeColor("teal3");
            pole11.moveHorizontal(530);
            pole11.moveVertical(280);
            pole11.changeSize(30);
            pole11.makeVisible();
            pole12.changeColor("teal3");
            pole12.moveHorizontal(530);
            pole12.moveVertical(310);
            pole12.changeSize(30);
            pole12.makeVisible();
            pole13.changeColor("teal3");
            pole13.moveHorizontal(530);
            pole13.moveVertical(340);
            pole13.changeSize(30);
            pole13.makeVisible();
            pole14.changeColor("teal3");
            pole14.moveHorizontal(530);
            pole14.moveVertical(370);
            pole14.changeSize(30);
            pole14.makeVisible();
            pole15.changeColor("teal3");
            pole15.moveHorizontal(530);
            pole15.moveVertical(400);
            pole15.changeSize(30);
            pole15.makeVisible();
            pole16.changeColor("teal3");
            pole16.moveHorizontal(530);
            pole16.moveVertical(430);
            pole16.changeSize(30);
            pole16.makeVisible();

            pole17.changeColor("teal3");
            pole17.moveHorizontal(610);
            pole17.moveVertical(250);
            pole17.changeSize(30);
            pole17.makeVisible();
            pole18.changeColor("teal3");
            pole18.moveHorizontal(610);
            pole18.moveVertical(280);
            pole18.changeSize(30);
            pole18.makeVisible();
            pole19.changeColor("teal3");
            pole19.moveHorizontal(610);
            pole19.moveVertical(310);
            pole19.changeSize(30);
            pole19.makeVisible();
            pole20.changeColor("teal3");
            pole20.moveHorizontal(610);
            pole20.moveVertical(340);
            pole20.changeSize(30);
            pole20.makeVisible();
            pole21.changeColor("teal3");
            pole21.moveHorizontal(610);
            pole21.moveVertical(370);
            pole21.changeSize(30);
            pole21.makeVisible();
            pole22.changeColor("teal3");
            pole22.moveHorizontal(610);
            pole22.moveVertical(400);
            pole22.changeSize(30);
            pole22.makeVisible();
            pole23.changeColor("teal3");
            pole23.moveHorizontal(610);
            pole23.moveVertical(430);
            pole23.changeSize(30);
            pole23.makeVisible();

            pole24.changeColor("teal3");
            pole24.moveHorizontal(690);
            pole24.moveVertical(250);
            pole24.changeSize(30);
            pole24.makeVisible();
            pole25.changeColor("teal3");
            pole25.moveHorizontal(690);
            pole25.moveVertical(280);
            pole25.changeSize(30);
            pole25.makeVisible();
            pole26.changeColor("teal3");
            pole26.moveHorizontal(690);
            pole26.moveVertical(310);
            pole26.changeSize(30);
            pole26.makeVisible();
            pole27.changeColor("teal3");
            pole27.moveHorizontal(690);
            pole27.moveVertical(340);
            pole27.changeSize(30);
            pole27.makeVisible();
            pole28.changeColor("teal3");
            pole28.moveHorizontal(690);
            pole28.moveVertical(370);
            pole28.changeSize(30);
            pole28.makeVisible();
            pole29.changeColor("teal3");
            pole29.moveHorizontal(690);
            pole29.moveVertical(400);
            pole29.changeSize(30);
            pole29.makeVisible();
            pole30.changeColor("teal3");
            pole30.moveHorizontal(690);
            pole30.moveVertical(430);
            pole30.changeSize(30);
            pole30.makeVisible();


            //left side bush
            bush.changeColor("green2");
            bush.moveHorizontal(40);
            bush.moveVertical(410);
            bush.changeSize(30);
            bush.makeVisible();
            bush2.changeColor("green2");
            bush2.moveHorizontal(69);
            bush2.moveVertical(410);
            bush2.changeSize(30);
            bush2.makeVisible();
            bush3.changeColor("green2");
            bush3.moveHorizontal(98);
            bush3.moveVertical(410);
            bush3.changeSize(30);
            bush3.makeVisible();
            bush4.changeColor("green2");
            bush4.moveHorizontal(127);
            bush4.moveVertical(410);
            bush4.changeSize(30);
            bush4.makeVisible();
            bush5.changeColor("green2");
            bush5.moveHorizontal(156);
            bush5.moveVertical(410);
            bush5.changeSize(30);
            bush5.makeVisible();
            bush6.changeColor("green2");
            bush6.moveHorizontal(185);
            bush6.moveVertical(410);
            bush6.changeSize(30);
            bush6.makeVisible();
            bush7.changeColor("green2");
            bush7.moveHorizontal(55);
            bush7.moveVertical(395);
            bush7.changeSize(30);
            bush7.makeVisible();
            bush8.changeColor("green2");
            bush8.moveHorizontal(84);
            bush8.moveVertical(395);
            bush8.changeSize(30);
            bush8.makeVisible();
            bush9.changeColor("green2");
            bush9.moveHorizontal(84);
            bush9.moveVertical(395);
            bush9.changeSize(30);
            bush9.makeVisible();
            bush10.changeColor("green2");
            bush10.moveHorizontal(113);
            bush10.moveVertical(395);
            bush10.changeSize(30);
            bush10.makeVisible();
            bush11.changeColor("green2");
            bush11.moveHorizontal(142);
            bush11.moveVertical(395);
            bush11.changeSize(30);
            bush11.makeVisible();
            bush12.changeColor("green2");
            bush12.moveHorizontal(171);
            bush12.moveVertical(395);
            bush12.changeSize(30);
            bush12.makeVisible();

            //right side bush                                                                                                                            9
            bush13.changeColor("green2");
            bush13.moveHorizontal(474);
            bush13.moveVertical(500);
            bush13.changeSize(50);
            bush13.makeVisible();
            bush14.changeColor("green2");
            bush14.moveHorizontal(515);
            bush14.moveVertical(500);
            bush14.changeSize(50);
            bush14.makeVisible();
            bush15.changeColor("green2");
            bush15.moveHorizontal(555);
            bush15.moveVertical(500);
            bush15.changeSize(50);
            bush15.makeVisible();
            bush16.changeColor("green2");
            bush16.moveHorizontal(595);
            bush16.moveVertical(500);
            bush16.changeSize(50);
            bush16.makeVisible();
            bush17.changeColor("green2");
            bush17.moveHorizontal(635);
            bush17.moveVertical(500);
            bush17.changeSize(50);
            bush17.makeVisible();
            bush18.changeColor("green2");
            bush18.moveHorizontal(675);
            bush18.moveVertical(500);
            bush18.changeSize(50);
            bush18.makeVisible();
            bush19.changeColor("green2");
            bush19.moveHorizontal(715);
            bush19.moveVertical(500);
            bush19.changeSize(50);
            bush19.makeVisible();
            bush20.changeColor("green2");
            bush20.moveHorizontal(755);
            bush20.moveVertical(500);
            bush20.changeSize(50);
            bush20.makeVisible();
            bush21.changeColor("green2");
            bush21.moveHorizontal(795);
            bush21.moveVertical(500);
            bush21.changeSize(50);
            bush21.makeVisible();
            bush22.changeColor("green2");
            bush22.moveHorizontal(495);
            bush22.moveVertical(470);
            bush22.changeSize(50);
            bush22.makeVisible();
            bush23.changeColor("green2");
            bush23.moveHorizontal(535);
            bush23.moveVertical(470);
            bush23.changeSize(50);
            bush23.makeVisible();
            bush24.changeColor("green2");
            bush24.moveHorizontal(575);
            bush24.moveVertical(470);
            bush24.changeSize(50);
            bush24.makeVisible();
            bush25.changeColor("green2");
            bush25.moveHorizontal(615);
            bush25.moveVertical(470);
            bush25.changeSize(50);
            bush25.makeVisible();
            bush26.changeColor("green2");
            bush26.moveHorizontal(655);
            bush26.moveVertical(470);
            bush26.changeSize(50);
            bush26.makeVisible();
            bush27.changeColor("green2");
            bush27.moveHorizontal(695);
            bush27.moveVertical(470);
            bush27.changeSize(50);
            bush27.makeVisible();
            bush28.changeColor("green2");
            bush28.moveHorizontal(735);
            bush28.moveVertical(470);
            bush28.changeSize(50);
            bush28.makeVisible();
            bush29.changeColor("green2");
            bush29.moveHorizontal(775);
            bush29.moveVertical(470);
            bush29.changeSize(50);
            bush29.makeVisible();
            bush30.changeColor("green2");
            bush30.moveHorizontal(535);
            bush30.moveVertical(470);
            bush30.changeSize(50);
            bush30.makeVisible();

            //right side plant wall
            plantwall.changeColor("peach");
            plantwall.moveHorizontal(385);
            plantwall.moveVertical(500);
            plantwall.changeSize(40);
            plantwall.makeVisible();
            plantwall2.changeColor("peach");
            plantwall2.moveHorizontal(425);
            plantwall2.moveVertical(500);
            plantwall2.changeSize(40);
            plantwall2.makeVisible();
            plantwall3.changeColor("peach");
            plantwall3.moveHorizontal(465);
            plantwall3.moveVertical(500);
            plantwall3.changeSize(40);
            plantwall3.makeVisible();
            plantwall4.changeColor("peach");
            plantwall4.moveHorizontal(505);
            plantwall4.moveVertical(500);
            plantwall4.changeSize(40);
            plantwall4.makeVisible();
            plantwall5.changeColor("peach");
            plantwall5.moveHorizontal(545);
            plantwall5.moveVertical(500);
            plantwall5.changeSize(40);
            plantwall5.makeVisible();
            plantwall6.changeColor("peach");
            plantwall6.moveHorizontal(585);
            plantwall6.moveVertical(500);
            plantwall6.changeSize(40);
            plantwall6.makeVisible();
            plantwall7.changeColor("peach");
            plantwall7.moveHorizontal(615);
            plantwall7.moveVertical(500);
            plantwall7.changeSize(40);
            plantwall7.makeVisible();
            plantwall8.changeColor("peach");
            plantwall8.moveHorizontal(655);
            plantwall8.moveVertical(500);
            plantwall8.changeSize(40);
            plantwall8.makeVisible();
            plantwall9.changeColor("peach");
            plantwall9.moveHorizontal(695);
            plantwall9.moveVertical(500);
            plantwall9.changeSize(40);
            plantwall9.makeVisible();
            plantwall10.changeColor("peach");
            plantwall10.moveHorizontal(735);
            plantwall10.moveVertical(500);
            plantwall10.changeSize(40);
            plantwall10.makeVisible();

            //left side plant wall
            plantwall11.changeColor("peach");
            plantwall11.moveHorizontal(-70);
            plantwall11.moveVertical(395);
            plantwall11.changeSize(35);
            plantwall11.makeVisible();
            plantwall12.changeColor("peach");
            plantwall12.moveHorizontal(-35);
            plantwall12.moveVertical(395);
            plantwall12.changeSize(35);
            plantwall12.makeVisible();
            plantwall13.changeColor("peach");
            plantwall13.moveHorizontal(0);
            plantwall13.moveVertical(395);
            plantwall13.changeSize(35);
            plantwall13.makeVisible();
            plantwall14.changeColor("peach");
            plantwall14.moveHorizontal(35);
            plantwall14.moveVertical(395);
            plantwall14.changeSize(35);
            plantwall14.makeVisible();
            plantwall15.changeColor("peach");
            plantwall15.moveHorizontal(70);
            plantwall15.moveVertical(395);
            plantwall15.changeSize(35);
            plantwall15.makeVisible();
            plantwall16.changeColor("peach");
            plantwall16.moveHorizontal(105);
            plantwall16.moveVertical(395);
            plantwall16.changeSize(35);
            plantwall16.makeVisible();
            plantwall17.changeColor("peach");
            plantwall17.moveHorizontal(135);
            plantwall17.moveVertical(395);
            plantwall17.changeSize(35);
            plantwall17.makeVisible();
            squareroof3.changeColor("brown");
            squareroof3.moveHorizontal(551);
            squareroof3.moveVertical(51);
            squareroof3.changeSize(199);
            squareroof3.makeVisible();
            squareroof4.changeColor("brown");
            squareroof4.moveHorizontal(355);
            squareroof4.moveVertical(51);
            squareroof4.changeSize(199);
            squareroof4.makeVisible();
            squareroof5.changeColor("brown");
            squareroof5.moveHorizontal(160);
            squareroof5.moveVertical(51);
            squareroof5.changeSize(199);
            squareroof5.makeVisible();
            squareroof6.changeColor("brown");
            squareroof6.moveHorizontal(-35);
            squareroof6.moveVertical(51);
            squareroof6.changeSize(199);
            squareroof6.makeVisible();
            squareroof7.changeColor("brown");
            squareroof7.moveHorizontal(-50);
            squareroof7.moveVertical(51);
            squareroof7.changeSize(199);
            squareroof7.makeVisible();
            whiteroof.changeColor("white");
            whiteroof.changeSize(100, 300);
            whiteroof.moveHorizontal(685);
            whiteroof.moveVertical(100);
            whiteroof.makeVisible();
            tealroof.changeColor("teal");
            tealroof.changeSize(75, 240);
            tealroof.moveHorizontal(685);
            tealroof.moveVertical(115);
            tealroof.makeVisible();




            handle.changeColor("gray");
            handle.moveHorizontal(300);
            handle.moveVertical(390);
            handle.changeSize(20);
            handle.makeVisible();
            sun.changeColor("yellow");
            sun.moveHorizontal(895);
            sun.moveVertical(-30);
            sun.changeSize(110);
            sun.makeVisible();
            person.changeColor("yellow");
            person.moveHorizontal(350);
            person.moveVertical(325);
            person.changeSize(100,50);
            person.makeVisible();

            drawn = true;
        }
    }

    /**
     * Change this picture to black/white display
     */
    public void setBlackAndWhite()
    {
        tealwall.changeColor("black");
        window.changeColor("white");
        roof.changeColor("black");
        sun.changeColor("black");
    }

    /**
     * Change this picture to use color display
     */
    public void setColor()
    {
        tealwall.changeColor("red");
        window.changeColor("black");
        roof.changeColor("green");
        sun.changeColor("yellow");
    }
}
